# full

In [5]:
import pandas as pd
metrics_df = pd.read_csv("classification_full_metrics_results.csv", index_col=0)
metrics_df

                    Accuracy  Precision    Recall  F1-score   ROC AUC
RandomForest        0.800000   0.783696  0.746041  0.758894  0.888292
XGBoost             0.806452   0.787272  0.760841  0.770981  0.871606
LightGBM            0.780645   0.755087  0.731618  0.740445  0.871795
LogisticRegression  0.806452   0.790329  0.755845  0.768149  0.903846
GradientBoosting    0.806452   0.798672  0.745852  0.761978  0.889329

In [4]:
feature_df = pd.read_csv("classification_full_feature_importance_results.csv", index_col=0)
feature_df

,RandomForest,XGBoost,LightGBM,LogisticRegression,GradientBoosting
청약경쟁률,0.240501,0.263800,469,0.120000,0.346599
의무보유확약비율,0.170089,0.133170,408,0.040000,0.159954
(확정)공모가격,0.120990,0.135037,296,0.021290,0.153354
대표매매감정점수,0.118213,0.104578,286,0.043871,0.111737
보호예수 비율,0.097342,0.086843,345,0.003226,0.097118
최대주주 소유주 비율,0.092016,0.076472,306,0.000645,0.047583
KOSPI_1001,0.076805,0.068209,306,0.000000,0.052162
DLR,0.051178,0.096964,103,-0.000645,0.019419
최대주주 보호예수 기간,0.032864,0.034927,48,-0.006452,0.012074